# Generated by Django 3.0 on 2021-11-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
