# Generated by Django 3.0 on 2021-11-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=200)),
                ('msg', models.TextField(max_length=200)),
            ],
        ),
    ]
