# Generated by Django 3.0 on 2021-11-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='phone',
            new_name='roll',
        ),
    ]
