# Generated by Django 3.0 on 2021-11-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0002_auto_20211118_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='invigilator',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
